### ISSUE TITLE
How to get Community to work?

### ISSUE THREAD

**Issue by enlewof** [AddonScriptorDE/plugin.video.screen_yahoo_com#1]
Hi there,

I'm trying to watch Community (https://screen.yahoo.com/community/) with the Yahoo Screen add on you have provided, which works with other videos except Community.  Oddly the previews on the channel work.   Here's the log entry for when I try to watch the second episode:

`13:36:21 T:2961911808  NOTICE: Thread LanguageInvoker start, auto delete: false
13:36:21 T:2961911808  NOTICE: -->Python Interpreter Initialized<--
13:36:21 T:2961911808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('streams',)
                                            Traceback (most recent call last):
                                              File "/Users/alew/Library/Application Support/XBMC/addons/plugin.video.screen_yahoo_com/default.py", line 398, in <module>
                                                playVideo(url, language)
                                              File "/Users/alew/Library/Application Support/XBMC/addons/plugin.video.screen_yahoo_com/default.py", line 274, in playVideo
                                                for stream in content['query']['results']['mediaObj'][0]['streams']:
                                            KeyError: ('streams',)
                                            -->End of Python script error report<--
13:36:21 T:2692448680   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.screen_yahoo_com/?url=b3d54ad2-0d4c-3f6d-9e28-7b880a30de77&mode=playVideo&language=en-US]
13:36:21 T:2961911808  NOTICE: Thread BackgroundLoader start, auto delete: false`

I have some experience working on XBMC addons, but not a lot.  I can probably help debug this a bit if can you give me some clues.  I'm guessing they're doing something different with the JSON for these videos, but can't see it (would love to know how to get better at debugging these video urls).  Can you take a look?  Thanks in advance.

**Comment by enlewof** [comment]
Looks like it works now.  Yahoo must have changed something.
